import firebase_admin

from firebase_admin import credentials
from firebase_admin import auth

#Inicializa el SDK firebase

cred = credentials.Certificate('/home/marcos/PycharmProjects/API-Gateway/ubademy-apigateway-firebase-adminsdk-hbeag-c06eb7278c.json')
default_app = firebase_admin.initialize_app(cred)
id_project = default_app.project_id
print(id_project)
id_token='eyJhbGciOiJSUzI1NiIsImtpZCI6IjY5NGNmYTAxOTgyMDNlMjgwN2Q4MzRkYmE2MjBlZjczZjI4ZTRlMmMiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiUk9HR0VSIEFMREFJUiBQQVJFREVTIFRBVkFSQSIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQVRYQUp3ekxtMjFzUTlreDdBMTJTbTN3djBJVzh1eHJOVk56ZXlLdnpzUz1zOTYtYyIsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS91YmFkZW15LWFwaWdhdGV3YXkiLCJhdWQiOiJ1YmFkZW15LWFwaWdhdGV3YXkiLCJhdXRoX3RpbWUiOjE2MzYxNTg2MDEsInVzZXJfaWQiOiIxcjZDZ0V2RkVkYVBFZkkxUUNzT09KcmROMjQyIiwic3ViIjoiMXI2Q2dFdkZFZGFQRWZJMVFDc09PSnJkTjI0MiIsImlhdCI6MTYzNjE1ODYwMSwiZXhwIjoxNjM2MTYyMjAxLCJlbWFpbCI6InJwYXJlZGVzdEBmaS51YmEuYXIiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJnb29nbGUuY29tIjpbIjExMzg4MjIzNzQ5NTc3NjkyNjAzOSJdLCJlbWFpbCI6WyJycGFyZWRlc3RAZmkudWJhLmFyIl19LCJzaWduX2luX3Byb3ZpZGVyIjoiZ29vZ2xlLmNvbSJ9fQ.efYEUeEQorU76J9jRW32McAPm5nnW45TbC74tuxR_IDlXRGts5IeweUdaSqnBlxTVzXxvLUz21_KZpwEwLACbBvC2V3gS7jjMLNeIiLdlIUj1cJ0oR_rZ8Il949pPHrFEqw78QiYSAeoq__gr2FO_FXclojE5g2yCKm9ED2_sB5zTGnIMdk_cLLaR8KVNhaojWJYPfGzfrvenkFfBDQcrrJsAnf8eSNQIBtluGyYfC17mBgOCVLbSvdyCSzEazpGwV7Odn4wJRazZwNWazrVPq_72K3-qgGbrSQy386GtcvQtXtMzvrodhHynPmpMh5KnCbdo1jAu6T3B7dFwL4Wlg'
    #'eyJhbGciOiJSUzI1NiIsImtpZCI6IjE1MjU1NWEyMjM3MWYxMGY0ZTIyZjFhY2U3NjJmYzUwZmYzYmVlMGMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdWJhZGVteS1hcGlnYXRld2F5IiwiYXVkIjoidWJhZGVteS1hcGlnYXRld2F5IiwiYXV0aF90aW1lIjoxNjM1Nzg3NDgxLCJ1c2VyX2lkIjoiZTRIaFQ3WmdLamZOUWRyYkxMbXBSeUFKWjZIMyIsInN1YiI6ImU0SGhUN1pnS2pmTlFkcmJMTG1wUnlBSlo2SDMiLCJpYXQiOjE2MzU3ODc0ODEsImV4cCI6MTYzNTc5MTA4MSwiZW1haWwiOiJtcm9tZXJvdkBmaS51YmEuYXIiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsibXJvbWVyb3ZAZmkudWJhLmFyIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.QAN5ziSmdblcSE-y3V3vcpURv-DVwOT_PZVKasL5QUWyVsyoIZy75VXb4I0tX6MZ-R_xK7lAoN6AhSUT8_tg8CK0WrOYxfJ_ox1mJBKs7bOPBeWHWqbDNdIlZPzjXH7_8jiD7qOjk2vpyauG8ZtiLxbcvtB1hGS02Ewt0pNsMHYaLdHGvkHVkgDzrIHpoFbStnG6M_7swetKBUw0LBZR6NLPlrTD2jDuAM0Eiq9sobzCZYYcaAoxbabqegIDvpjYiJjSFZHHoREtkurunInf-Dv8Fe6Jj22Km1ynb-mQQ-nmOtdBx1lt1noh8ySfeeKeBR5lFIH1gMczaGOwaoyM1w'
try:
   decoded_token = auth.verify_id_token(id_token, default_app)
   aud = decoded_token['aud']   #uid
   if aud == id_project:
            print( "Id del proyecto confimada ud", aud)
except:
           print('Token invalido o vencido')





